name: Linux CI

on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      - "**:**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  TRAVIS_OS_NAME: linux
  SPEC_SPLIT_DOTS: 160

jobs:
  # Test against latest release and the earliest supported Crystal version for forward compatibility.
  #
  # A more advanced test which runs against *each* supported version is available in `forward-compatibility.yml` and
  # runs regularly on a nightly schedule.
  x86_64-gnu-test:
    env:
      ARCH: x86_64
      ARCH_CMD: linux64
      DOCKER_TEST_PREFIX: crystallang/crystal:${{ matrix.crystal_bootstrap_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: [""]
        include:
          # libffi is only available starting from the 1.2.2 build images
          - crystal_bootstrap_version: 1.0.0
            flags: "FLAGS=-Dwithout_ffi USE_PCRE1=true"
          - crystal_bootstrap_version: 1.15.1 # LATEST RELEASE
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v4

      - name: Prepare System
        run: bin/ci prepare_system

      - name: Prepare Build
        run: bin/ci prepare_build

      - name: Test
        run: ${{ matrix.flags }} bin/ci build

  x86_64-musl-test:
    env:
      ARCH: x86_64-musl
      ARCH_CMD: linux64
    runs-on: ubuntu-latest
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v4

      - name: Prepare System
        run: bin/ci prepare_system

      - name: Prepare Build
        run: bin/ci prepare_build

      - name: Test
        run: bin/ci build

  x86_64-gnu-test-preview_mt:
    env:
      ARCH: x86_64
      ARCH_CMD: linux64
    runs-on: ubuntu-latest
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v4

      - name: Prepare System
        run: bin/ci prepare_system

      - name: Prepare Build
        run: bin/ci prepare_build

      - name: Make Crystal
        run: bin/ci with_build_env 'make crystal'

      - name: Test
        run: bin/ci with_build_env 'CRYSTAL_WORKERS=4 make std_spec threads=1 FLAGS="-D preview_mt"'

  check_format:
    env:
      ARCH: x86_64
      ARCH_CMD: linux64
    runs-on: ubuntu-latest
    steps:
      - name: Download Crystal source
        uses: actions/checkout@v4

      - name: Prepare System
        run: bin/ci prepare_system

      - name: Prepare Build
        run: bin/ci prepare_build

      - name: Check Format
        run: bin/ci format
