name: Test Full

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/test-full.yml
  schedule:
  - cron: '0 3 * * *'

permissions: {}

jobs:
  call-forward_compatibility:
    uses: ./.github/workflows/forward-compatibility.yml

  call-llvm:
    uses: ./.github/workflows/llvm.yml

  call-smoke_tests:
    uses: ./.github/workflows/smoke.yml
